sudo: false
language: generic
services:
  - docker
env:
  global:
    - DIGEST=3d98c20c3b109ccdfbdfc298a1cd204011f7998a190f5e8c6c451ba8851ffc3c
jobs:
  include:
    - stage: exec scrapbook
      if: branch = master
      script: git clone -b master "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" temp
      after_success:
        - cd temp
        - docker run --rm -v `pwd`:/work matsubara0507/scrapbook@sha256:${DIGEST} scrapbook -o . -t feed sites.yaml
        - git config user.name "${GIT_NAME}"
        - git config user.email "${GIT_EMAIL}"
        - git status
        - git add -A
        - git diff --quiet && git diff --staged --quiet || git commit -am "[skip ci] Update scrapbook"
        - git push origin master
